### ISSUE TITLE
highlight代码高亮错误

### ISSUE THREAD

**Issue by 2515299122** [xaoxuu/hexo-theme-volantis#451]
### 第一步：查阅文档 

- [ ] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [ ] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

A. 能正常运行，代表主题和当前环境配置都没有问题。
B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

- [x] 测试结果是：A or B

### 截图

<details><summary>相关截图</summary>

![image](https://user-images.githubusercontent.com/59388668/90948688-bce94e80-e473-11ea-95b7-e770c86da80e.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```

#### 主题配置文件
```yml
highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.2/styles/darcula.css
```

#### node.js & npm
```
C:\Users\bingbing\Desktop\bingbing2>node -v
v12.18.1

C:\Users\bingbing\Desktop\bingbing2>npm -v
6.14.8
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>
