### ISSUE TITLE
我想要整体居中的表格，我应该怎么设置？

### ISSUE THREAD

**Issue by Firestar-Reimu** [xaoxuu/hexo-theme-volantis#688]
现在表格整体是左对齐的

https://volantis.js.org/page/5/ 上面也是左对齐的

我没有在文档里面找到对表格的设置，我想要表格在文章左右居中，应当如何设置？

**Comment by Firestar-Reimu** [comment]
已解决

Markdown 表格：

在正文里面加入：

```css
<style>
table{
margin:0 auto;
display: revert !important:
}
```

HTML 表格
```html
<div align="center">
</div>
```
