### ISSUE TITLE
长公式渲染超出范围

### ISSUE THREAD

**Issue by Firestar-Reimu** [xaoxuu/hexo-theme-volantis#689]
渲染器：https://github.com/Menci/hexo-renderer-syzoj-renderer

问题：长公式渲染会超出范围，且无法通过任何方法把挡住的部分显示出来

解决办法：https://zhuanlan.zhihu.com/p/110427092

```css
.formula{
  width: 100%;
  overflow-x: auto
}
```
![26db780e9a2893a3](https://user-images.githubusercontent.com/65082432/141939636-3b5d5d62-81a3-4f58-974c-58bbe256692c.jpg)

建议把这个内置在theme中（虽然我不知道是theme的问题还是renderer的问题但是渲染器是没有CSS的）

另外一个解决方法是渲染器换成hexo-renderer-kramed
