### ISSUE TITLE
希望增加关闭摘要功能

### ISSUE THREAD

**Issue by Firestar-Reimu** [xaoxuu/hexo-theme-volantis#691]
例如：文章摘要
开关自动摘要（默认开启）：
```
index:
  auto_excerpt:
    enable: true
```

也就是把这部分关掉
![屏幕截图 2021-11-26 104605](https://user-images.githubusercontent.com/65082432/143519028-297fd690-3b99-406a-b2fd-40ed215730d6.png)

**Comment by inkss** [comment]
```yml
article:
  preview:
    hide_excerpt: true
```

同时文章页不设置 `<!-- more -->`, `excerpt` 和 `description`。
