### ISSUE TITLE
侧边栏webinfo部件部分功能开关异常

### ISSUE THREAD

**Issue by Lyrikp** [xaoxuu/hexo-theme-volantis#707]
## 预期与实际表现的区别

无法在侧边栏中关闭webinfo的访客与流量统计

## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。您当前使用的volantis版本为：5.0.0-alpha.5_________________
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. `_config.volantis.yml`中`sidebar`项中配置`widget_library:`，复制官网文档 `webinfo`部件代码，将`siteuv`和`sitepv`的`enable`项设置为`false`，渲染后仍输出访客数和访问量

### 复现地址：

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图:</summary>
<img width="1402" alt="截屏2022-01-21 15 22 44" src="https://user-images.githubusercontent.com/69946241/150484032-732ff418-15e4-4811-b2f7-65ba7d64f277.png">

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
sidebar:
  for_page: [qgroup, post, category, guide, webinfo]
  for_post: [toc]
  widget_library:
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fas fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2020/01/01'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: false
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        siteuv:
          enable: false
          text: '本站访客数：'   # 需要启用 busuanzi
          unit: '人'
        sitepv:
          enable: false
          text: '本站总访问量：' # 需要启用 busuanzi
          unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'

```
