### ISSUE TITLE
Uncaught ReferenceError: volantis is not defined

### ISSUE THREAD

**Issue by penndu** [xaoxuu/hexo-theme-volantis#709]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

### 主题版本

您当前使用的版本为：dev

### 复现地址

dusays.com

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![image](https://user-images.githubusercontent.com/46226528/151039624-6ac0ca1a-0cd9-467d-acd1-20bef7f76187.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml

  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, counter] #启用评论数量需在此添加
    top_meta: [author, category, date, counter, walinecount, wordcount] #启用评论数量需在此添加
    # ----------------
    # 文章页脚组件
    footer_widget:
@@ -452,14 +452,18 @@ comments:
  waline:
    js: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是waline的问题
    placeholder: 快来评论吧~  # 评论占位提示
    imageHosting: https://7bu.top/api/upload # 图床api（默认使用去不图床）
    placeholder: 评论支持贴图，大家在截图后，在评论框粘贴，自动传至图床~  # 评论占位提示

    imageHosting: https://7bu.top/api/upload?token=9723fbead34e8263a16ef690c4622acc # 图床api（默认使用去不图床）
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder uploadImage] 选项
    meta: [nick,mail,link] # waline comment header info
    requiredFields: [nick,mail]
    serverURL: https://n.dusays.com # Waline 的服务端地址（必填） 测试用地址: https://waline-ruddy.vercel.app
    avatar: robohash # gravatar style https://waline.js.org/client/basic.html#avatar
    avatarCDN: #https://sdn.geekzu.org/avatar/
    emoji: [
      'https://cdn.dusays.com/gh/zhheo/Sticker-Heo@latest/Sticker-100/',
    ]
    pageSize: 10 # 评论每页显示数量
    lang: zh-CN
    visitor: true
@@ -471,9 +475,10 @@ comments:
sidebar:
  position: right # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud, donate]
  for_page: [blogger, zanzhu, sffw, vpsor, cowtransfer, tui_jian, dao_hang, category, tagcloud, webinfo]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  for_post: [blogger, toc, zanzhu, sffw, vpsor, cowtransfer, tui_jian, dao_hang, category, tagcloud, webinfo]

  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
@@ -546,6 +551,146 @@ sidebar:
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    zanzhu:
      class: text
      display: [desktop, mobile]
      header:
        icon: fas fa-wallet
        title: 点击赞助
      content:
        - '<center><a href="https://afdian.net/@teacherdu"><img src="https://cdn.dusays.com/yf.jpg-2"></a><center>'
    sffw:
      class: text
      display: [desktop, mobile]
      header:
        icon: fas fa-dollar-sign
        title: 收费服务
        url: https://dusays.com/sffw
      content:
        - '<center><a href="https://dusays.com/sffw"><img src="https://cdn.dusays.com/sffw.gif"></a><center>'
    vpsor:
      class: text
      display: [desktop, mobile]
      header:
        icon: fas fa-cloud
        title: 硅云主机
        url: https://www.vpsor.cn?userCode=ohedb8
      content:
        - '<center><a href="https://www.vpsor.cn?userCode=ohedb8" target="_blank"><img src="https://cdn.dusays.com/vpsor.jpg-2"></a><center>'
    cowtransfer:
      class: text
      display: [desktop, mobile]
      header:
        icon: fas fa-upload
        title: 阿里云盘
        url: https://pages.aliyundrive.com/mobile-page/web/beinvited.html?code=616d4cf
      content:
        - '<center><a href="https://pages.aliyundrive.com/mobile-page/web/beinvited.html?code=616d4cf" target="_blank"><img src="https://cdn.dusays.com/aliyundrive.jpg-2"></a></center>'
    dao_hang:
      class: grid
      display: [desktop, mobile]
      header:
        icon: fas fa-map-signs
        title: 站内导航
      fixed: true # 固定宽度
      rows:
        - name: 近期文章
          icon: fas fa-clock
          url: /
        - name: 文章归档
          icon: fas fa-archive
          url: archives/
        - name: 我的友链
          icon: fas fa-link
          url: friends/
        - name: 关于小站
          icon: fas fa-info-circle
          url: about/
        - name: 文章分类
          icon: fas fa-book
          url: categories/
        - name: 热门标签
          icon: fas fa-fire
          url: tags/
    tui_jian:
      class: list
      display: [desktop, mobile]
      header:
        icon: fas fa-thumbs-up
        title: 友情链接
        url: /friends/
      rows:
        - name: 贝贝吧
          img: https://cdn.dusays.com/avatar.png
          url: http://www.hibbba.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: Colsrch
          img: https://cdn.dusays.com/gh/Colsrch/images/Colsrch/avatar.jpg
          url: https://colsrch.cn/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 勤奋的思远
          img: https://bu.dusays.com/2020/11/10/ab1185891b443.png
          url: https://lsybk.xyz/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: Blogin
          img: https://bu.dusays.com/2020/11/13/b54215c2293a9.jpg
          url: http://2dogz.cn/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 易学堂
          img: https://cdn.dusays.com/avatar.png
          url: https://www.qqeg.cn/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 科研软件小站
          img: https://bu.dusays.com/2021/08/25/6ea5def2f92c9.jpg
          url: https://www.sciencesoft.cn/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 梦之国
          img: https://cdn.dusays.com/avatar.png
          url: https://www.achivedreams.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 林林杂语
          img: https://cdn.dusays.com/avatar.png
          url: https://www.linlinzzo.top/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 周良粥凉
          img: https://cdn.dusays.com/avatar.png
          url: https://imzl.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: R0A1NG’s blog
          img: https://cdn.dusays.com/avatar.png
          url: https://www.roaing.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: Dr.Pika’s Blog
          img: https://cdn.dusays.com/avatar.png
          url: https://blog.drpika.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 秋木小站
          img: https://qiumuu.gitee.io/mdchat/ico/3.jpg
          url: https://www.qiumu.club/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 我的世界中文站
          img: https://cdn.dusays.com/avatar.png
          url: https://www.minecraftzw.com/
          rel: external nofollow noopener noreferrer
          target: _blank
        - name: 杜老师说
          img: https://cdn.dusays.com/avatar.png
          url: http://dusays.com/
        - name: 友链申请
          img: https://cdn.dusays.com/avatar.png
          url: http://dusays.com/friends/
    # webinfo widget
    webinfo:
      class: webinfo
@@ -688,7 +833,7 @@ plugins:

  ######## Plugins to optimize the experience:
  # 代码高亮
  code_highlight: highlightjs # highlightjs or prismjs
  code_highlight: prismjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true
@@ -724,7 +869,7 @@ plugins:
  ######## Plugins for SEO:
  # npm i hexo-wordcount
  wordcount:
    enable: #true
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
@@ -806,7 +951,7 @@ plugins:
    animation: false # false, nprogress, circle
    nprogress: /libs/@nprogress/nprogress.min.js # https://cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/artitalk/'   # artitalk 不支持 pjax
      - '/shuoshuo/'   # artitalk 不支持 pjax
      # - '/bbtalk/'     # bbtalk 不支持 pjax

  # 暗黑模式 darkmode
@@ -838,18 +983,21 @@ plugins:
    # 不支持 Pjax
    # 配置项按照yml格式继续填写即可
    js: https://cdn.jsdelivr.net/npm/artitalk
    appId: ogP8qj3veMh0LFpFWMPOyF0X-MdYXbMMI # your appID
    appKey: nHXLd3N3Jgh460t2iRQKWAtr # your appKEY
    # serverURL:  #leancloud绑定的api访问域名，使用国际版的话不需要填写
    appId: 38GEBsbldifhQHRcJvVTrIjd-gzGzoHsz # your appID

    appKey: XLpNu93zlTMOQsCtOmpniJwi # your appKEY
    serverURL: https://s.dusays.com #leancloud绑定的api访问域名，使用国际版的话不需要填写
    # lang: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # pageSize: #每页说说的显示数量
    # shuoPla: #在编辑说说的输入框中的占位符
    # avatarPla: #自定义头像url的输入框的占位符
    # motion: #加载动画的开关，1为开，0为关，默认为开
    # bgImg: #说说输入框背景图片url
    # color1: #说说背景颜色1&按钮颜色1
    # color2: #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
    color1: 'linear-gradient(90deg,rgba(247,149,51,.1) 0,rgba(243,112,85,.1) 15%,rgba(239,78,123,.1) 30%,rgba(161,102,171,.1) 44%,rgba(80,115,184,.1) 58%,rgba(16,152,173,.1) 72%,rgba(7,179,155,.1) 86%,rgba(109,186,130,.1) 100%)' #说说背景颜色1&按钮颜色1
    color2: 'linear-gradient(90deg,rgba(247,149,51,.1) 0,rgba(243,112,85,.1) 15%,rgba(239,78,123,.1) 30%,rgba(161,102,171,.1) 44%,rgba(80,115,184,.1) 58%,rgba(16,152,173,.1) 72%,rgba(7,179,155,.1) 86%,rgba(109,186,130,.1) 100%)' #说说背景颜色2&按钮颜色2


    color3: '#5e5e5e' #说说字体颜色
    # cssUrl: #自定义css接口

  # BBtalk https://bb.js.org
@@ -958,7 +1106,7 @@ plugins:
############################### Rightmenu ############################### > start
# 自定义右键菜单
rightmenu:
  enable: true
  enable: false
  faicon: fa              # 公共图标类型 fa fal fas fad
  # hr: 分割线, music: 音乐控制器
  layout: [home, hr, help, examples, contributors, hr, source_docs, source_theme, hr, print, darkmode, reading, music]
```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
你之前的某次合并可能覆盖过什么

**Comment by inkss** [comment]
![杜老师说 - Google Chrome_22-01-26_08-26-19](https://user-images.githubusercontent.com/31947043/151082281-053d53df-4432-4857-b8cc-455d28dd1e9a.png)

之前为了方便在 js 里调主题的配置，有加这个：
https://github.com/volantis-x/hexo-theme-volantis/blob/2af5fd7d9a2b87be42735803b2078bd8845cfcb8/layout/_partial/scripts/global.ejs#L4-L5

"This is a picture without description" 是这里加的：
https://github.com/volantis-x/hexo-theme-volantis/blob/87b7427b5e8d8d4895391f06939436a5c7acde50/scripts/filters/seo.js#L3-L12

你的配置文件里 [图片](https://github.com/penndu/hexo-theme-volantis/blob/66171b24b1cc830f6cf0a76251fc3b1f6be8ec62/_config.yml#L552-L559) 估计就这样被处理了:

```yml
zanzhu:
  class: text
  display: [desktop, mobile]
  header:
    icon: fas fa-wallet
    title: 点击赞助
  content:
    - '<center><a href="https://afdian.net/@teacherdu"><img src="https://cdn.dusays.com/yf.jpg-2"></a><center>'
```

@MHuiG 问问怎么过滤这个？
