### ISSUE TITLE
【问题】：busuanzi无法正确渲染uv、pv

### ISSUE THREAD

**Issue by ek1ng** [xaoxuu/hexo-theme-volantis#735]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0.0-rc.3

### 复现地址

https://ek1ng.com

### 问题描述

busuanzi网络请求正常，但是博客侧边栏的uv、pv无法正确渲染，文章顶栏的浏览量可以正确渲染

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ek1ng's Blog
subtitle: ''
description: foucs on security and web development
keywords:
author: ek1ng
language: zh-CN
timezone: Asia/Shanghai
favicon: img/default/avatar.ico

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ek1ng.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: 

```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
use_cdn: false

default:
  avatar: /img/default/avatar.jpg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

navbar:
  logo: # choose [img] or [icon + title]
    img: '' #https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title: ek1ng
  search: 想找些什么~
  menu:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /

    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/

    - name: 标签
      icon: fad fa-folder-open CONCRETE faa-vertical
      url: /tags/

    - name: 友链
      icon: fad fa-stamp POMEGRANATE faa-vertical
      url: /friends/  

    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

    - name: 更多
      icon: fa-duotone fa-ellipsis-v
      rows:
        - name: 虫洞
          description: 十年之约，探索虫洞
          icon: fad fa-bullseye-pointer BELIZEHOLE faa-vertical
          url: https://www.foreverblog.cn/go.html

        - name: 源码
          icon: fad fa-code-merge WISTERIA faa-vertical
          url: https://github.com/ek1ng/blog


cover:
  # height_scheme: full # full, half
  title: ek1ng's blog
  subtitle: Foucs on security and web development
  background: # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  features:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /
    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/
    - name: 标签
      icon: fad fa-folder-open CONCRETE faa-vertical
      url: /tags/
    - name: 友链
      icon: fad fa-stamp POMEGRANATE faa-vertical
      url: /friends/
    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

article:
  preview:
    # scheme: landscape # landscape
    # # pin icon for post
    # pin_icon: # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # # auto generate title if not exist
    # auto_title: false # false, true
    # # auto generate excerpt if not exist
    # auto_excerpt: false # false, true
    # author: true
    # # show readmore button
    # readmore: auto # auto, always
      line_style: hidden
  body:
    meta_library:
      author:
        avatar: https://ek1ng-typora.oss-cn-hangzhou.aliyuncs.com/img/avatar.jpg
        name: ek1ng
        url: https://github.com/ek1ng/
      updated:
        title: '本页文档最后更新于：'


comments:
  service: valine
  valine:
    # js: https://npm.elemecdn.com/valine@1.4/dist/Valine.min.js
    path: /
    placeholder: 快来评论吧~  # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: ThEuM29Rc9YmToV1iVFhGyAQ-gzGzoHsz
    appKey: yOtNPLW34jnOwf7vlJuOiEFL

sidebar:
  for_page: [blogger, lastupdate, tagcloud, webinfo]
  for_post: [toc]
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.jpg
      shape: circle # circle, rectangle
      url: /about/
      title: ek1ng
      subtitle: 
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fad fa-clock WISTERIA
        title: 随机推荐
    toc:
      display: [desktop, mobile]
      header:
        icon: fad fa-list ASBESTOS
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fad fa-tags WISTERIA 
        url: /tags/
      max_font: 24
      min_font: 16
    webinfo:
      display: [desktop]
      header:
        icon: fad fa-award NEPHRITIS
      type:
        runtime:
          data: '2021/3/15'
        wordcount:
          unit: ''
        visitcounter:
          siteuv:
            enable: true
          sitepv:
            enable: true

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [aplayer, social, source, analytics, copyright]
  copyright: '[Copyright © 2017-2021 Volantis Team](https://github.com/volantis-x/) [浙ICP备2021038365号-2
](https://beian.miit.gov.cn/)'
  social:
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/020-rss.svg
      url: atom.xml
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/029-github.svg
      url: https://github.com/volantis-x/
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/010-facebook.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/018-twitter.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/045-telegram.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/006-youtube.svg
      url: /

plugins:
  clipboard:
    enable: true
  fontawesome: /libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  gitter:
    room: hexo-theme-volantis/community
  wordcount:
    enable: true
    
analytics:
  busuanzi: /libs/busuanzi/js/busuanzi.pure.mini.js
  leancloud: # 请使用自己的 id & key 以防止数据丢失
    app_Id: 
    app_Key: 

custom_css:
  cursor:
    enable: true
  font_smoothing: true
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal

rightmenu:
  enable: true
  faicon: fa-duotone PETERRIVE             # 公共图标类型 fa fal fas fad
  # hr: 分割线, music: 音乐控制器
  layout: [home, hr, print, reading, darkmode, music]
  ### 可选功能项 ###
  print:                  # 只有文章页才允许自定义打印
    name: 打印页面
    icon: fa-duotone fa-print TURQUOISE
    defaultStyles: true   # 是否使用预制的打印样式
    # js:                 # 自定义 js ，可用于修饰打印样式~， 右键剔除了对 Jquery 的依赖，所以此处你只能使用原生 js
    #  - document.querySelector('article#comments').remove()  # 移除评论
  darkmode:        # 需开启 plugins.darkmodejs
    name: 暗黑模式
    icon: fa-duotone fa-eclipse-alt WISTERIA
  customPicUrl:    # 右键的图片复制：只有 Chrome 支持，且只支持 PNG 格式的图片。
    enable: false  # 如果使用了对象存储且开启了自适应 Webp，那么可以提供额外的链接用以替换图片的访问地址
    old: #https://static.inkss.cn/img/article/
    new: #https://cdn.jsdelivr.net/gh/inkss/inkss-cdn@master/img/article/  
  ### 自定义菜单 ###
  reading:
    name: 阅读模式
    icon: fa-duotone fa-book-open PETERRIVE
  
pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v14.17.2
6.14.13
```

</p></details>

<details><summary>package.json</summary><p>

```
hexo-site@0.0.0 C:\Users\xxxxxx\Desktop\projects\blog
+-- hexo@6.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.3
+-- hexo-generator-tag@1.0.0
+-- hexo-related-popular-posts@5.0.1
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@5.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@3.0.0
+-- hexo-theme-landscape@0.0.3
+-- hexo-theme-volantis@5.0.0-rc.3
`-- hexo-wordcount@6.0.1
```

</p></details>

**Comment by MHuiG** [comment]
```yml
sidebar:
  widget_library:
    webinfo:
      type:
        visitcounter:
          service: busuanzi  # busuanzi, leancloud
```
