### ISSUE TITLE
【问题】：5.00-rc.4更新到5.00-rc.10后hexo generate报错

### ISSUE THREAD

**Issue by ek1ng** [xaoxuu/hexo-theme-volantis#739]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.00-rc.10

### 复现地址

https://ek1ng.com

### 问题描述

这是我的[博客仓库](https://github.com/ek1ng/blog)，目前使用rc.4运行正常，更新版本后hexo generate报错，已经回滚至rc.4版本，本地环境和远程环境更新版本后hexo generate都报错。
![image](https://user-images.githubusercontent.com/72065582/163702637-4d71fa92-9541-422b-9425-4eef19328c01.png)
以下是我的本地环境的hexo node等相关版本
```
hexo: 6.1.0
hexo-cli: 4.3.0
os: win32 10.0.22000 
node: 17.9.0
v8: 9.6.180.15-node.16
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 3.0.2+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
以下是我github action的配置
```
name: Hexo博客持续集成

on: 
  push:
    branches:
      - main
      
jobs:
  build: 
    runs-on: ubuntu-latest 

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@master

    - name: 安装Node.js 16.x 
      uses: actions/setup-node@master
      with:
        node-version: "16.x"

    - name: 安装Hexo依赖
      run: |
        npm install hexo-cli -g
        npm install
    - name: 构建Hexo
      run: |
        hexo clean
        hexo generate
        
    - name: 部署到云服务器
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "./public/"
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: "/home/www/hexo/"
```

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ek1ng's Blog
subtitle: ''
description: foucs on security and web development
keywords:
author: ek1ng
language: zh-CN
timezone: Asia/Shanghai
favicon: img/default/avatar.ico

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ek1ng.com
permalink: :title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#RSS订阅
# Extensions
plugins:
  hexo-generator-feed
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#修改行内代码块字体
import:
  link:
    - <link href="https://cdn.jsdelivr.net/gh/inkss/common@1/css/roboto.min.css" rel="stylesheet" media="print" onload="this.media='all'">
    - <link href="https://cdn.jsdelivr.net/gh/inkss/common@1/css/jetbrains.min.css" rel="stylesheet" media="print" onload="this.media='all'">
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
use_cdn: false

default:
  avatar: /img/default/avatar.jpg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

navbar:
  logo: # choose [img] or [icon + title]
    img: '' #https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title: ek1ng
  search: 想找些什么~
  menu:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /

    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/

    - name: 友链
      icon: fad fa-stamp CONCRETE faa-vertical
      url: /friends/  

    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

    - name: 更多
      icon: fa-duotone fa-ellipsis-v
      rows:
        - name: 虫洞
          description: 十年之约，探索虫洞
          icon: fad fa-bullseye-pointer BELIZEHOLE faa-vertical
          url: https://www.foreverblog.cn/go.html

        - name: 源码
          icon: fad fa-code-merge WISTERIA faa-vertical
          url: https://github.com/ek1ng/blog


cover:
  # height_scheme: full # full, half
  title: ek1ng's blog
  subtitle: Foucs on security and web development
  background: # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  features:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /
    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/
    - name: 友链
      icon: fad fa-stamp CONCRETE faa-vertical
      url: /friends/
    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: /media/twemoji/assets/svg/1f4cc.svg # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # hide excerpt
    hide_excerpt: false
    # show split line or not
    line_style: hidden # hidden, solid, dashed, dotted
    # show author
    author: false # true, false
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, counter] #启用评论数量需在此添加
    # ----------------
    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fa-solid fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: false
        title: 相关文章
        icon: fa-solid fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
      # ----------------
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true
        permalink: '本文永久链接是：'
        content:
          - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          - permalink
      # ----------------
      # 打赏组件 (for layout: post)
      donate:
        enable: false
        images:
          - /media/org.volantis/blog/qrcode/github@volantis.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
          - /media/org.volantis/blog/qrcode/github@volantis.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags, share]
    # meta library
    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: /media/org.volantis/blog/favicon/apple-touch-icon.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: ek1ng
        url: /
      # 文章创建日期
      date:
        icon: fa-solid fa-calendar-alt
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fa-solid fa-edit
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fa-solid fa-folder-open
      # 文章浏览计数
      counter:
        icon: fa-solid fa-eye
        unit: '次浏览'
      # waline 文章评论数量
      walinecount:
        icon: fa-solid fa-comment-dots
        desc: '' # 条评论
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fa-solid fa-keyboard
        icon_duration: fa-solid fa-hourglass-half
      # 文章标签
      tags:
        icon: fa-solid fa-hashtag
      # 分享
      share:
        - id: qq
          img:  /media/org.volantis/logo/128/qq.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
        - id: qzone
          img: /media/org.volantis/logo/128/qzone.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
        - id: weibo
          img: /media/org.volantis/logo/128/weibo.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
        - id: # qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
          img: # /media/org.volantis/logo/128/wechat.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
        - id: # telegram
          img: # /media/org.volantis/logo/128/telegram.png #  https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png

comments:
  service: valine
  valine:
    # js: https://npm.elemecdn.com/valine@1.4/dist/Valine.min.js
    path: /
    placeholder: 快来评论吧~  # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: ThEuM29Rc9YmToV1iVFhGyAQ-gzGzoHsz
    appKey: yOtNPLW34jnOwf7vlJuOiEFL

sidebar:
  for_page: [blogger, lastupdate, tagcloud, webinfo]
  for_post: [toc]
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.jpg
      shape: circle # circle, rectangle
      url: /about/
      title: ek1ng
      subtitle: 
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fad fa-clock WISTERIA
        title: 近期更新
    toc:
      display: [desktop, mobile]
      header:
        icon: fad fa-list ASBESTOS
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fad fa-tags WISTERIA 
        url: /tags/
      max_font: 24
      min_font: 16
    webinfo:
      display: [desktop]
      header:
        icon: fad fa-award NEPHRITIS
      type:
        runtime:
          data: '2021/3/15'
        wordcount:
          unit: ''
        visitcounter:
          service: busuanzi
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: false
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [aplayer, social, copyright]
  copyright: '[Copyright © 2020-2022](https://github.com/ek1ng/) [浙ICP备2021038365号-2
](https://beian.miit.gov.cn/)'
    # site source
  source: https://github.com/ek1ng/blog
  social:
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/020-rss.svg
      url: atom.xml
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/029-github.svg
      url: https://github.com/ek1ng/
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/010-facebook.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/018-twitter.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/045-telegram.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/006-youtube.svg
      url: /

plugins:
  clipboard:
    enable: true
  fontawesome: /libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  gitter:
    room: hexo-theme-volantis/community
  wordcount:
    enable: true
    
analytics:
  busuanzi: /libs/busuanzi/js/busuanzi.pure.mini.js
  leancloud: # 请使用自己的 id & key 以防止数据丢失
    app_Id: 
    app_Key: 

custom_css:
  cursor:
    enable: true
  font_smoothing: true
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Roboto,"Noto Serif SC","Microsoft Yahei",sans-serif,Menlo,Monaco,monospace,sans-serif'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Roboto,"Noto Serif SC","Microsoft Yahei",sans-serif,Menlo,Monaco,monospace,sans-serif'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    codefont:
      fontfamily: 'JetBrainsMono,ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace'

rightmenu:
  enable: true
  faicon: fa-duotone PETERRIVE             # 公共图标类型 fa fal fas fad
  # hr: 分割线, music: 音乐控制器
  layout: [home, hr, print, reading, darkmode, music]
  ### 可选功能项 ###
  print:                  # 只有文章页才允许自定义打印
    name: 打印页面
    icon: fa-duotone fa-print TURQUOISE
    defaultStyles: true   # 是否使用预制的打印样式
    # js:                 # 自定义 js ，可用于修饰打印样式~， 右键剔除了对 Jquery 的依赖，所以此处你只能使用原生 js
    #  - document.querySelector('article#comments').remove()  # 移除评论
  darkmode:        # 需开启 plugins.darkmodejs
    name: 暗黑模式
    icon: fa-duotone fa-eclipse-alt WISTERIA
  customPicUrl:    # 右键的图片复制：只有 Chrome 支持，且只支持 PNG 格式的图片。
    enable: false  # 如果使用了对象存储且开启了自适应 Webp，那么可以提供额外的链接用以替换图片的访问地址
    old: #https://static.inkss.cn/img/article/
    new: #https://cdn.jsdelivr.net/gh/inkss/inkss-cdn@master/img/article/  
  ### 自定义菜单 ###
  reading:
    name: 阅读模式
    icon: fa-duotone fa-book-open PETERRIVE
  
pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v17.9.0
8.5.5
```

</p></details>

<details><summary>package.json</summary><p>

```
hexo-site@0.0.0 C:\Users\76104\Desktop\projects\blog
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.3
├── hexo-generator-sitemap@3.0.1
├── hexo-generator-tag@1.0.0
├── hexo-neat@1.0.9
├── hexo-related-popular-posts@5.0.1
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
├── hexo-theme-volantis@5.0.0-rc.10
├── hexo-wordcount@6.0.1
└── hexo@6.1.0
```

</p></details>
