### ISSUE TITLE
waline2

### ISSUE THREAD

**Issue by zryyyy** [xaoxuu/hexo-theme-volantis#757]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0.0-alpha.111

### 复现地址

https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml#L408

### 问题描述

![](https://i.bmp.ovh/imgs/2022/05/13/44b7c3c67d071011.png)
下图是不改引入地址之前的评论区
![](https://i.bmp.ovh/imgs/2022/05/13/fa7a13485a95b938.png)
改完引入地址以后是这样
![](https://i.bmp.ovh/imgs/2022/05/13/f7c6b5a0501ae186.png)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
js: https://unpkg.com/@waline/client@2.4.2/dist/waline.js # https://unpkg.com/@waline/client@v2/dist/waline.js
css: https://unpkg.com/@waline/client@2.4.2/dist/waline.css # https://unpkg.com/@waline/client@v2/dist/waline.css
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>
