### ISSUE TITLE
【问题】：友链朋友圈无法显示

### ISSUE THREAD

**Issue by BeaCox** [xaoxuu/hexo-theme-volantis#765]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.0.1

### 复现地址

https://bowenyoung.cn/fcircle

### 问题描述

按照最新的配置文件配置友链朋友圈fcircle时，发现本应显示友链朋友圈处只有一个卡片，只有在第一次进入时一闪而过的文字内容。不知道是pjax的问题还是其他问题。感谢百忙中抽空解答！

### 配置文件

<details><summary>主题配置文件</summary><p>

```yml
  fcircle:
    # Set `plugins: ["fcircle"]` to enable in front-matter
    # 支持 Pjax
    api: 'https://********' # api 地址
    message: '与主机通讯中……'  # 占位文字
    css: 'https://fastly.jsdelivr.net/gh/lmm214/immmmm/themes/hello-friend/static/fcircle-beta.css'
    js: 'https://fastly.jsdelivr.net/gh/lmm214/immmmm/themes/hello-friend/static/fcircle-beta.js'
```

</p></details>

fcircle.md中front matter配置
```
layout: page
bottom_meta: false
sidebar: [blogger, repos, lastupdate, tagcloud, webinfo]
plugins: ["fcircle"]
```

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v16.14.2
8.5.0

```

</p></details>

<details><summary>package.json</summary><p>

```
├── bindings@1.5.0 extraneous
├── bulma-stylus@0.8.0
├── file-uri-to-path@1.0.0 extraneous
├── hexo-abbrlink@2.2.1
├── hexo-component-inferno@1.1.0
├── hexo-deployer-git@3.0.0
├── hexo-filter-github-emojis@3.0.5
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-searchdb@1.4.0
├── hexo-generator-sitemap@3.0.1
├── hexo-generator-tag@1.0.0
├── hexo-helper-qrcode@1.0.2
├── hexo-pagination@2.0.0
├── hexo-related-popular-posts@5.0.1
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-inferno@0.1.3
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@3.0.0
├── hexo-theme-volantis@5.1.0
├── hexo-wordcount@6.0.1
├── hexo@6.1.0
└── nan@2.15.0 extraneous

```

</p></details>
