### ISSUE TITLE
【问题】：目录中标题显示不完整

### ISSUE THREAD

**Issue by ElainaFanBoy** [xaoxuu/hexo-theme-volantis#831]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://www.ch3rry.cn/posts/IRONY.html

### 问题描述

![P 0UXYYO{_PZP{J}OL 15YJ](https://user-images.githubusercontent.com/56375835/205435121-b0198bb8-0dd2-4a18-a136-31a8f47affb8.jpg)
![JCKHB@ 8WF48KB61ENUP6TU](https://user-images.githubusercontent.com/56375835/205435210-5690ea82-abb8-454d-96f9-9bc0b2c409fa.jpg)

我的文章里第1个二级标题里有3个三级标题，其中第1个三级标题里有40个四级标题，但是点开第1个三级标题desktop和mobile中都无法全部显示，只能显示到第38个，并且一直到下一个二级目录之前，后面的三级目录和四级目录都显示不出来

复现地址：https://www.ch3rry.cn/posts/IRONY.html

仓库地址：https://github.com/NanakoOfficial/Ch3rry.github.io

### 配置文件

<details><summary>主题配置文件</summary><p>

```yml
toc:
  class: toc
  display: [desktop, mobile] # [desktop, mobile]
  sticky: true
  header:
    icon: fa-solid fa-list
    title: 本文目录
  list_number: false
  min_depth: 2
  max_depth: 5
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
node v16.17.0
npm 8.15.0
```

</p></details>

<details><summary>package.json</summary><p>

```
hexo 6.3.0
```

</p></details>

<details><summary>Volantis</summary><p>

```
hexo-theme-volantis 5.7.7
```

</p></details>

**Comment by Tikas** [comment]
本想复现一下，去仓库地址，clone 回来竟然发现是已编译的静态文件，好吧，这还真仓库哇。

以现有的信息，非常抱歉，我无法在本地复现您这出现的情况

**Comment by ElainaFanBoy** [comment]
> 本想复现一下，去仓库地址，clone 回来竟然发现是已编译的静态文件，好吧，这还真仓库哇。
> 
> 以现有的信息，非常抱歉，我无法在本地复现您这出现的情况

呜呜我是直接本地部署git推上去的，那我直接发您我本地的文件可以吗

**Comment by ElainaFanBoy** [comment]
> 本想复现一下，去仓库地址，clone 回来竟然发现是已编译的静态文件，好吧，这还真仓库哇。
> 
> 以现有的信息，非常抱歉，我无法在本地复现您这出现的情况

[myblog.zip](https://github.com/volantis-x/hexo-theme-volantis/files/10150020/myblog.zip)

**Comment by MHuiG** [comment]
```css
#l_side .toc-wrapper .toc-item.active>.toc-child {
    max-height: 20000px !important;
}
```
原来是 max-height: 1000px;

![image](https://user-images.githubusercontent.com/38281581/205539831-526b2b37-5043-4179-a521-b95f61dc82c0.png)
