### ISSUE TITLE
【建议】：

### ISSUE THREAD

**Issue by Ezgx** [xaoxuu/hexo-theme-volantis#848]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [X] 已经阅读 hexo 官方文档，未发现原生支持。

### 需求描述

导航栏一点的优化

### 参考链接
```css
.l_header.auto.show {
    box-shadow: 0px 0px 10px 5px #666666;
    top: 15px;
    border-radius: 20px;
}
```
