### ISSUE TITLE
【问题】：本地预览加载不了css

### ISSUE THREAD

**Issue by xingpingcn** [xaoxuu/hexo-theme-volantis#865]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://xingpingcn.github.io/

### 问题描述

部署在GitHub上面的页面没有问题，但是本地预览的网页加载不了css

![image](https://user-images.githubusercontent.com/117259690/232851379-8026aec0-735c-4fcf-8a48-cfedb95c9149.png)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
cdn:
  enable: false
  # CDN 前缀，为空使用默认值，链接最后不加 "/",
  # 例如： https://cdn.jsdelivr.net/gh/volantis-x/volantis-x.github.io@gh-page 填写最后编译生成的源码CDN地址前缀，此路径下应该含有/js与/css目录,
  # 该配置默认值是："https://unpkg.com/hexo-theme-volantis@"+ theme.info.theme_version +"/source"
  prefix: #https://unpkg.com/hexo-theme-volantis/source
  # 以下配置可以覆盖 cdn.prefix,配置项的值可以为空，但是要使用CDN必须依据路径填写配置项的键
  set:
    js:
      app: #/js/app.js
    css:
      style: #/css/style.css # (异步加载样式)
# 静态资源版本控制
# 本地文件使用文件内容的hash值作为版本号(app.8c1e7c88.js)  其他为时间戳 (?time=1648684470140)
# 建议静态资源设置标头 浏览器缓存一年边缘缓存一个月 cache-control: max-age=86400, s-maxage=31536000 如果有更新记得刷新缓存
cdn_version: false
# volantis static 静态资源文件 npm 包 CDN 地址 (后面加 "/" )
# https://github.com/volantis-x/volantis-static
volantis_static_cdn: https://unpkg.com/volantis-static@0.0.1654736714924/
########################################################################
#  https://web.dev/content-visibility/
#  https://www.caniuse.com/?search=content-visibility
content_visibility: false

# 全局页面字符串替换  A => B (可用于临时修改错字等)
replace:
  - https://cdn.jsdelivr.net/npm/ => https://unpkg.com/
  - https://cdn.jsdelivr.net/gh/ => https://gcore.jsdelivr.net/gh/

```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
v18.16.0
9.5.1
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
-- hexo-generator-json-content@4.2.3
```

</p></details>
