### ISSUE TITLE
【问题】：使用cdn.jsdelivr.net/gh/加速css有几率导致显示不全

### ISSUE THREAD

**Issue by xingpingcn** [xaoxuu/hexo-theme-volantis#868]
### 检查清单

- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] #869
- [x] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://cdn.jsdelivr.net/gh/xingpingcn/website.comments/style.css

### 问题描述

![image](https://user-images.githubusercontent.com/117259690/233567228-950b5d70-42cd-4d55-95f3-49489f4b1261.png)

如图，首页没有文章（直连的时候加载慢，每次强制刷新都会复现；如果走v2ray代理，加载快，则不会复现此情况），这时再刷新（f5）就有了。异步加载css的时候能加载sidebar，但是似乎没有加载文章list

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
cdn:
  enable: true
  # CDN 前缀，为空使用默认值，链接最后不加 "/",
  # 例如： https://cdn.jsdelivr.net/gh/volantis-x/volantis-x.github.io@gh-page 填写最后编译生成的源码CDN地址前缀，此路径下应该含有/js与/css目录,
  # 该配置默认值是："https://unpkg.com/hexo-theme-volantis@"+ theme.info.theme_version +"/source"
  # prefix: #https://unpkg.com/hexo-theme-volantis/source/
  prefix: #https://jsd.cdn.zzko.cn/gh/xingpingcn/website.comments
  # 以下配置可以覆盖 cdn.prefix,配置项的值可以为空，但是要使用CDN必须依据路径填写配置项的键
  set:
    js:
      app: https://jsd.cdn.zzko.cn/gh/xingpingcn/website.comments/app.js
    css:
      style: https://cdn.jsdelivr.net/gh/xingpingcn/website.comments/style.css # (异步加载样式)
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>
