### ISSUE TITLE
【反馈】：为什么配置文件中 injects.first注入的样式无效

### ISSUE THREAD

**Issue by lovelyJason** [xaoxuu/hexo-theme-volantis#872]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [ ] 主题官网也存在这个问题。

### 复现步骤

我想引入一个css文件，比如文件的路径为：主题theme/source/css/iconfont.css, 就是一些字体图标，内容为

![image](https://user-images.githubusercontent.com/50656459/233780767-cdb413dd-0825-40b1-a826-61abf1d566f6.png)

我想在first.styl中注入， 因此配置文件_config.volantis.yml里配置了
```yml
injects:
  first:  # first注入无效？
    - iconfont.css
```

first.styl的源码：

![image](https://user-images.githubusercontent.com/50656459/233781503-a9b381c3-7b8c-426d-9d77-73e5fd008406.png)

按道理来说，自定义的样式上应该是会被追加到尾部的吧

然后我重启后看到的页面上是没有这个css的， 我去主题源码中的FirstCSS这个help函数中查看，看看first.styl编译后的代码是什么

![image](https://user-images.githubusercontent.com/50656459/233780852-e2a7ee9e-ecc3-4104-9876-1c4c9dbd4992.png)

然后我尝试将配置项中的first改为style

```yml
injects:
  style: 
    - iconfont.css
```

这个时候样式是生效的，查看网站上的/css/style.css样式表是有追加内容进去的

我看volantis文档上的注入点是这样的

![image](https://user-images.githubusercontent.com/50656459/233781098-7e856396-94d5-4a8a-b14e-184971ae6253.png)

唯一不同是first样式是内嵌样式， 为什么会有这种情况出现

### 配置文件

_config.volantis.yml
```yml
############################### injects ############################### > start
injects:
  first:  # first注入无效？
    - iconfont.css
############################### injects ############################### > end
```

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v18.12.0
8.19.2
```

</p></details>

<details><summary>package.json</summary><p>

```
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo@5.4.0
```

</p></details>
