### ISSUE TITLE
【问题】：github action 部署后所有页面index内容为空

### ISSUE THREAD

**Issue by cunyu1943** [xaoxuu/hexo-theme-volantis#896]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://github.com/cunyu1943/cunyu1943.github.io/blob/volantis

### 问题描述

- 本地 hexo server 正常

<img width="1254" alt="image" src="https://github.com/volantis-x/hexo-theme-volantis/assets/22308895/08b25a54-c299-43fd-b3dc-acfc66daefaf">

- github action 生成后

<img width="1030" alt="image" src="https://github.com/volantis-x/hexo-theme-volantis/assets/22308895/00b76987-3b63-423c-a978-9a28db1a6bae">

### 配置文件

```yml
name: 自动部署
# 当有改动推送到master分支时，启动Action
on:
  push:
    branches:
      - main
      # 2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: 缓存 Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 安装依赖
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install --save

      - name: 生成静态文件
        run: |
          hexo clean
          hexo generate

      - name: 部署到Github
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          token: ${{ secrets.TOKEN }}
          repository-name: username/repo
          branch: volantis
          folder: public
          commit-message: "${{ github.event.head_commit.message }}"

```

### 环境信息
![image](https://github.com/volantis-x/hexo-theme-volantis/assets/22308895/def81492-fe84-424d-8834-cb5e26f0930e)

_No response_
