### ISSUE TITLE
【问题】：v6中memos插件请求的api地址有问题

### ISSUE THREAD

**Issue by musnows** [xaoxuu/hexo-theme-volantis#913]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://memos.musnow.top/

### 问题描述

使用的memos `v0.19.1`，对比sidebar中的memos请求和plugins中的memos请求会发现，sidebar中的请求是对的。

当前所处主题的git hash为：` e53eae55a5f00ead3368fc95e87d7ebbe77ff157`；

## sidebar的配置如下

```yaml
# Memos widget
    memos_carousel:
      class: memos_carousel
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-volume-high
        title: 说说
        url: /memos/ # 说说页面的地址
      url: 'https://memos.musnow.top/' # 替换城自己的域名，也可以用杜老师的平台托管
      limit: '10' # 展示数量限制
      creatorId: '1' # 替换成自己的用户的ID
      tag: '' # 要展示的内容的标签
      image: 'fa-solid fa-image' # 图片替换成图标
      link: 'fa-solid fa-link' # 链接替换成图标
      placeholder: '说说加载中...' # 占位符
```

最终请求的地址是

```
https://memos.musnow.top/api/v1/memo?creatorId=1&tag=&limit=10
```

## plugins的配置如下

```yaml
  # Memos https://usememos.com
  memos:
    # Set `plugins: ["memos"]` to enable in front-matter
    url: 'https://memos.musnow.top/' # 替换成自己的域名，也可以用杜老师的平台托管
    limit: '10' # 展示数量限制
    id: '1' # 替换成自己的用户的ID
```

最终请求的地址是

```
https://memos.musnow.top/api/memo?creatorId=1&rowStatus=NORMAL&limit=10
```

这里plugins的请求是404的，因为请求路径中少了一个`/v1/`；

![image](https://github.com/volantis-x/hexo-theme-volantis/assets/87506951/50d6977a-310a-450c-b496-d25c66123ec8)

![image](https://github.com/volantis-x/hexo-theme-volantis/assets/87506951/6151fb56-7387-448d-a56e-896c4c8b87d0)

加上v1后可以正常访问结果。

![image](https://github.com/volantis-x/hexo-theme-volantis/assets/87506951/31d64251-d0c2-4a3b-b4a5-32db0c46b4c1)

### 配置文件

<details><summary>站点配置文件</summary><p>

上文已经提供

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
node v16.20.2
npm 8.19.4
```

</p></details>

<details><summary>package.json</summary><p>

```
hexo-site@0.0.0 D:\HEXO\test
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.1.0
├── hexo-server@3.0.0
└── hexo@5.4.2
```

</p></details>
