### ISSUE TITLE
【问题】：cover这里有个bug

### ISSUE THREAD

**Issue by lovelyJason** [xaoxuu/hexo-theme-volantis#918]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://www.qdovo.com

### 问题描述

如图, 这里代码逻辑错误
<img width="838" alt="image" src="https://github.com/volantis-x/hexo-theme-volantis/assets/50656459/c8b22176-1474-48af-98ba-03c837ad1b72">

你的意思是当配置了page.cover为true的时候在判断是否首页，是否prev=0，是否height_scheme=full都没用。因为博客首页的page.cover不可能为true, 即使在_post下新建index.md设置cover为true，hexo也不会读取。

<img width="978" alt="image" src="https://github.com/volantis-x/hexo-theme-volantis/assets/50656459/54edd122-d183-4d66-a82f-b3c98b9bb27e">

所以后果就是首页的cover永远不会显示，不管怎么配置， 因为首页page.cover这段if就进不来。

难道是我用错了？我记得之前版本不是这样， 解答一下疑惑

### 配置文件

<details><summary>主题配置文件</summary><p>

```yml
cover:
  logo: null
  title: qdovo
  height_scheme: full # full, half
  layout_scheme: dock # 

plugins:
  comment_typing: false
  # backstretch:
  # #   enable: false
  #   position: fixed
  #   images:             # For personal use only. At your own risk if used for commercial purposes !!!
  #     - https://cdn.qdovo.com/scenic/4456776-3705836a00587303.jpeg
  parallax:
    enable: true
    position: cover       
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息
```

</p></details>
