### ISSUE TITLE
【问题】：边栏位置调整不起作用

### ISSUE THREAD

**Issue by EarendelH** [xaoxuu/hexo-theme-volantis#922]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [ ] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://earendelh.github.io

### 问题描述

我在文件/EarendelH.github.io/_config.volantis.yml中修改sidebar的属性`position`为`left`，执行`hexo s`后本地服务器成功修改为左侧，但在`hexo d`部署后通过[https://earendelh.github.io](https://earendelh.github.io)链接访问博客时，边栏位置没有更改，我已尝试过清除浏览器缓存，并且通过同时修改shape，等待足够长时间的方法，确认不是部署时间过短的问题。
<img width="1181" alt="image" src="https://github.com/volantis-x/hexo-theme-volantis/assets/140391405/8eccf9aa-940e-44b6-bcd3-9f3f93d8ff71">

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
############################### Sidebar ############################### > start
sidebar:
  position: left # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud, donate]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: /images/authoricon.jpg # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      shape: rectangle # circle, rectangle
      url: /about/
      title: Earendel
      subtitle: 一名大一小萌新
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fa-solid fa-envelope
          url: mailto:1048872982@qq.com
        - icon: fab fa-github
          url: https://github.com/EarendelH/
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # music
    music:
      class: music
      display: [desktop, mobile] # [desktop, mobile]
      pjaxReload: false
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /blog/categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    # ---------------------------------------
    # qrcode widget
    qrcode:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px  # Automatic height if not set
      images:
        - volantis-static/media/org.volantis/blog/qrcode/github@volantis.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - volantis-static/media/org.volantis/blog/qrcode/github@volantis.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2024/03/13'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: false
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          enable: true
          siteuv:
            text: '本站访客数：'
            unit: '人'
          sitepv:
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    # ---------------------------------------
    # lastupdate widget
    lastupdate:
      class: lastupdate
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: 最近更新
############################### Sidebar ############################### > end
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
在这里粘贴替换 `node -v && npm -v` 输出的信息
v20.12.2
10.5.2
```

</p></details>

<details><summary>package.json</summary><p>

```
在这里粘贴替换 `npm ls --depth 0` 输出的信息

npm ERR! code ELSPROBLEMS
npm ERR! invalid: hexo-renderer-marked@6.2.0 /Users/earendelh/Blogs/EarendelH.github.io/node_modules/hexo-renderer-marked
npm ERR! invalid: hexo@7.1.1 /Users/earendelh/Blogs/EarendelH.github.io/node_modules/hexo
hexo-site@0.0.0 /Users/earendelh/Blogs/EarendelH.github.io
├── hexo-asset-image@0.0.5 (git+ssh://git@github.com/xcodebuild/hexo-asset-image.git#3c114cf0c0343ab28469635085b225fcae7fb9d3)
├── hexo-deployer-git@4.0.0
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.2.0 invalid: "^6.3.0" from the root project
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.0.0
├── hexo-theme-volantis@5.8.0
└── hexo@7.1.1 invalid: "^7.2.0" from the root project


npm ERR! A complete log of this run can be found in: /Users/earendelh/.npm/_logs/2024-04-23T07_29_27_514Z-debug-0.log

```

</p></details>
