### ISSUE TITLE
【反馈】：一系列问题

### ISSUE THREAD

**Issue by talefou** [xaoxuu/hexo-theme-volantis#923]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将主题升级到最新版本。
- [X] 主题官网也存在这个问题。

### 复现地址

https://vayfou.cn

### 复现步骤

- 文章开启 ```阅读模式``` 后顶部导航栏丢失
见下图：
![image](https://github.com/volantis-x/hexo-theme-volantis/assets/159092352/68bb6fff-5b4d-4d64-a01a-d0226e138c00)
```YML
custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    color: '#cccccc'
    hover: '#808080'
```
- 侧边栏模块添加阴影效果却不显示
```YML
  navbar:
    height: 64px
    width: auto
    effect: [shadow]
  sidebar:
    effect: [shadow]
  body:
    effect: [shadow]
```
见下图：
![image](https://github.com/volantis-x/hexo-theme-volantis/assets/159092352/6361076c-ec4a-42c1-a9e8-aeb6f95b1724)

### 配置文件

<details><summary>站点配置文件</summary><p>

```YML
custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    color: '#cccccc'
    hover: '#808080'
```

```YML
  navbar:
    height: 64px
    width: auto
    effect: [shadow]
  sidebar:
    effect: [shadow]
  body:
    effect: [shadow]
```

### 环境信息

<details><summary>Volantis</summary><p>

```
============================================================
  Volantis 6.0.0-alpha.1
  Docs: https://volantis.js.org/
  Repo: https://github.com/volantis-x/hexo-theme-volantis/
============================================================
```

**Comment by Tikas** [comment]
由于当前没有进一步在本地部署验证，就在线的效果进行初步检测，以下是检测结果：

## 文章开启【阅读模式】退出后顶部导航栏丢失

在这进一步详细复现步骤：

在文章页面，进入【阅读模式】后，随意在空白地方退出，顶部导航栏不显示。

### BUG 出现的原因：

进入【阅读模式】后，会在 `<header>` 标签增加样式：`style="opacity: 0;"`，同时也会在 `<div id="1_body">` 增加 `class="common_read"`

退出【阅读模式】时，只进行了 `<div id="1_body">` 的 `class=""` 清除，并没有对  `<header>` 标签做样式修改，`style="opacity: 0;"` 依旧存在，导致导航栏隐藏。

### BUG 解决方法：

在退出【阅读模式】时，同时对 `<header>` 标签进行 `style="opacity: 1;"` 操作

## 后续未能进行测试

对 ”文章移动端【文章目录】功能无法使用“，我对多个使用本主题的博客进行查看，都没有发现他们有使用【文章目录】，线上只能参考 https://vayfou.cn/ ，结果如大家所见。

从这一个开始，由于我没去配置本地调试，未能进一步测试，因为我在全心投入 Astro，暂时不想配对 Hexo 相关，这一步暂时交给其他人测试。

<blockquote><div><strong><a href="https://vayfou.cn/">Just a moment...</a></strong></div></blockquote>

**Comment by talefou** [comment]
> 由于当前没有进一步在本地部署验证，就在线的效果进行初步检测，以下是检测结果：
> 
> ## 文章开启【阅读模式】退出后顶部导航栏丢失
> 在这进一步详细复现步骤：
> 
> 在文章页面，进入【阅读模式】后，随意在空白地方退出，顶部导航栏不显示。
> 
> ### BUG 出现的原因：
> 进入【阅读模式】后，会在 `<header>` 标签增加样式：`style="opacity: 0;"`，同时也会在 `<div id="1_body">` 增加 `class="common_read"`
> 
> 退出【阅读模式】时，只进行了 `<div id="1_body">` 的 `class=""` 清除，并没有对 `<header>` 标签做样式修改，`style="opacity: 0;"` 依旧存在，导致导航栏隐藏。
> 
> ### BUG 解决方法：
> 在退出【阅读模式】时，同时对 `<header>` 标签进行 `style="opacity: 1;"` 操作
> 
> ## 后续未能进行测试
> 对 ”文章移动端【文章目录】功能无法使用“，我对多个使用本主题的博客进行查看，都没有发现他们有使用【文章目录】，线上只能参考 https://vayfou.cn/ ，结果如大家所见。
> 
> 从这一个开始，由于我没去配置本地调试，未能进一步测试，因为我在全心投入 Astro，暂时不想配对 Hexo 相关，这一步暂时交给其他人测试。
> 
> > **[Just a moment...](https://vayfou.cn/)**

抱歉，由于我的操作失误，```display``` 中，未将 ```mobile``` 开启导致 ```文章目录``` 无法使用问题，深感歉意。

<blockquote><div><strong><a href="https://vayfou.cn/">Just a moment...</a></strong></div></blockquote>

**Comment by talefou** [comment]
> 由于当前没有进一步在本地部署验证，就在线的效果进行初步检测，以下是检测结果：
> 
> ## 文章开启【阅读模式】退出后顶部导航栏丢失
> 在这进一步详细复现步骤：
> 
> 在文章页面，进入【阅读模式】后，随意在空白地方退出，顶部导航栏不显示。
> 
> ### BUG 出现的原因：
> 进入【阅读模式】后，会在 `<header>` 标签增加样式：`style="opacity: 0;"`，同时也会在 `<div id="1_body">` 增加 `class="common_read"`
> 
> 退出【阅读模式】时，只进行了 `<div id="1_body">` 的 `class=""` 清除，并没有对 `<header>` 标签做样式修改，`style="opacity: 0;"` 依旧存在，导致导航栏隐藏。
> 
> ### BUG 解决方法：
> 在退出【阅读模式】时，同时对 `<header>` 标签进行 `style="opacity: 1;"` 操作
> 
> ## 后续未能进行测试
> 对 ”文章移动端【文章目录】功能无法使用“，我对多个使用本主题的博客进行查看，都没有发现他们有使用【文章目录】，线上只能参考 https://vayfou.cn/ ，结果如大家所见。
> 
> 从这一个开始，由于我没去配置本地调试，未能进一步测试，因为我在全心投入 Astro，暂时不想配对 Hexo 相关，这一步暂时交给其他人测试。
> 
> > **[Just a moment...](https://vayfou.cn/)**

顶部导航栏(navbar)在关闭任何效果后，依旧显示阴影(shadow)效果，如何解决呢？

如图：
![image](https://github.com/user-attachments/assets/546e8530-0c12-4c03-a0e5-ff81a6fe0711)

复现地址：https://vayfou.cn

配置文件：
```yml
custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    color: '#cccccc'
    hover: '#808080'
  navbar:
    height: 64px
    width: auto
    effect: []
  sidebar:
    effect: []
  body:
    effect: []
```

主题修改仓库：https://github.com/talefou/volantis

**Comment by talefou** [comment]
经测试，对其添加任何效果（在 ```hexo clean``` 清除缓存以及 ```ctrl+f5``` 强制刷新后）均无反应。

1. scrollbar 滚动条在添加 color 和 hover 无效果；
2. navbar 添加 floatable 无浮起来效果/删除 floatable ('[]'中无任何添加效果)也依旧会显示 shadow 阴影效果。

配置如下：
```yml
custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    color: '#cccccc'
    hover: '#808080'
  navbar:
    height: 64px
    width: auto
    effect: [floatable]
```
