### ISSUE TITLE
【问题】：无法显示博客总访问量和访客数

### ISSUE THREAD

**Issue by chyyl** [xaoxuu/hexo-theme-volantis#930]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [x] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [x] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

https://yucuiyingqing.github.io/blog/new/

### 问题描述

页面底部无法显示博客总访问量和访客数

### 配置文件

<details><summary>主题配置文件</summary><p>

```yml
sidebar:
  widget_library:
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2024/08/14'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
v22.13.1
11.1.0
```

</p></details>

<details><summary>package.json</summary><p>

```
hexo-site@0.0.0 C:\Users\Administrator\Desktop\github\site\blog\new
+-- aplayer@1.10.1
+-- hexo-deployer-git@4.0.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@4.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@7.0.0
+-- hexo-renderer-stylus@3.0.1
+-- hexo-server@3.0.0
+-- hexo-theme-landscape@1.0.0
+-- hexo-theme-volantis@5.8.0
+-- hexo-wordcount@6.0.1
`-- hexo@7.3.0
```

</p></details>
