### ISSUE TITLE
【问题】：黑暗模式下搜索框失色

### ISSUE THREAD

**Issue by talefou** [xaoxuu/hexo-theme-volantis#934]
### 检查清单

- [x] 已经搜索过，没有发现类似 issue。
- [x] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [x] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

6.x

### 复现地址

https://vayfou.cn/

### 问题描述

- [vayfou](https://vayfou.cn)
![Image](https://github.com/user-attachments/assets/cb89e8cd-e1e4-46ce-b3d9-f47eb6047332)
- [澄沨](https://champhoon.xyz)
![Image](https://github.com/user-attachments/assets/5391caca-2f9d-410e-82fb-4d95bdf876f6)
- [qdovo](https://www.qdovo.com)
![Image](https://github.com/user-attachments/assets/d4bd9593-ef6d-4554-8825-02eb2a19ced7)

### 配置文件

```yml
color_scheme:
  common:
    theme: '#3dd9b6'
    link: '#2092ec'
    button: '#44d7b6'
    hover: '#ff5722'
    inner: '#fff'
    selection: 'alpha(#2196f3, 0.2)'
  light:
    site_bg: '#f9fafb'
    site_inner: '#fff'
    site_footer: '#666'
    card: '#fff'
    text: '#444'
    block: '#f6f6f6'
    codeblock: '#f4f4f4'
    inlinecode: '#444'
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'
    list: '#666'
    list_hl: 'mix($color-theme, #000, 80)'
    meta: '#888'
    copyright_bkg: '#f5f5f5'
  dark:
    site_bd: '#121212'
    site_bg: '#1f1f1f'
    card: '#262626'
    site_inner: '#eeeeeede'
    site_footer: '#aaaaaade'
    text: '#eeeeeede'
    block: '#1f1f1f'
    codeblock: '#1f1f1f'
    inlinecode: '#d56d28'
    h1: '#ffffffde'
    h2: '#ffffffde'
    h3: '#ffffff99'
    h4: '#ffffff99'
    h5: '#ffffff99'
    h6: '#ffffff99'
    p: '#d9d9d9de'
    list: '#d9d9d9de'
    list_hl: 'mix($color-theme, #fff, 80)'
    meta: '#bfbfbfde'
    copyright_bkg: '#21252b'
    brightness: 70%

custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    color: '#cccccc'
    hover: '#808080'
  navbar:
    height: 64px
    width: auto
    effect: [shadow]
  sidebar:
    effect: [shadow]
  body:
    effect: [shadow]
```

### 环境信息

```
INFO  Validating config
INFO  
============================================================
  Volantis 6.0.0-alpha.1
  Docs: https://volantis.js.org/
  Repo: https://github.com/volantis-x/hexo-theme-volantis/
============================================================
INFO  Start processing
INFO  Hexo is running at http://localhost:5500/ . Press Ctrl+C to stop.
```

**Comment by Tikas** [comment]
非常感谢您的反馈。

查看源码，发现 `--color-card: $color-dark-card` 是加载配置文件读取颜色值：

``` yml
  dark:
    site_bd: '#121212'
    site_bg: '#1f1f1f'
    card: '#262626'
```

从默认配置文件中可以发现，是加载 `card: '#262626'` 这个值。

我有想过把默认背景色改为 `site_bg`，然而 `:focus` 状态是 `site_bd: #121212` 的颜色，`site_bg: '#1f1f1f'` 和它的区别不大，此方案放弃。

默认的 `card: '#262626'` 很多地方都在引用，直接修改此值则会导致其他地方改变，此方案也放弃。

我也有想过把 `.nav-main .u-search-input` 的 `background` 直接改为 `#333`，从观感上，看起来不错，唯一不足就是字的对比不够：

![Image](https://github.com/user-attachments/assets/4bd06aec-5005-418d-ae6b-c1e738225705)

这方法虽然说可行，但是，没有考虑到自定义用户。

如果用户使用自己的配色方案，此值固定，将会进一步影响整体视觉效果，再次放弃。

要想更好的解决方案，或许需要额外指定一个新值去适配，此问题，理应加入待做。
